### ISSUE TITLE
Create backend high-level architecture 

### ISSUE THREAD

**Issue by lolagarden** [SE761Team4/jabref#11]
**User Story**
As a developer, I'd like a backend architecture for JabMaps, so that the backend can be developed

**Acceptance Criteria**

- Backend architecture describes how data storage and the backend will interact and behave
- Diagram created to show the architecture

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

**Describe the solution you'd like**

**Comment by koppor** [comment]
Please use FMC as notation

http://www.fmc-modeling.org/quick-intro

![grafik](https://user-images.githubusercontent.com/1366654/91341636-1508b380-e7da-11ea-81ad-d54cf36628b1.png)

Maybe create three diagrams:

- backend (JabRef)
- frontend (JabMap) - refs https://github.com/SE761Team4/jabref/issues/12
- both (show the interaction between)

**Comment by koppor** [comment]
Relates to #23

**Comment by koppor** [comment]
@lolagarden Could you possibly link the pull request or the file where one can see the result? 😇
