### ISSUE TITLE
[4pt] Create node in mindmap

### ISSUE THREAD

**Issue by lolagarden** [SE761Team4/jabref#15]
**User Story**
As a user, I'd like to create a node and give it a label, so that I can start my mindmap

**Acceptance Criteria**

- A node is created with a label
-

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

**Describe the solution you'd like**

**Comment by koppor** [comment]
Keyboard shortcuts:

- <kbd>Ins</kbd> - inserts a new node as child of the current node. In case children are existing, the new node is appended to the children
- <kbd>Enter</kbd> - inserts a new node below the current node
