### ISSUE TITLE
[4pt] Drag and drop JabRef references 

### ISSUE THREAD

**Issue by lolagarden** [SE761Team4/jabref#16]
**User Story**
As a user, I'd like to drag and drop references onto my mindmap, so that I can use my JabRef references

**Acceptance Criteria**

- Able to drag and drop JabRef references into JabMaps
-

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

**Describe the solution you'd like**

**Comment by koppor** [comment]
I can drop a reference...

- ... to create a new node (refs https://github.com/SE761Team4/jabref/issues/21)
- ... to create a link at an existing node
