### ISSUE TITLE
[8pt] Make JabMap interface prototype

### ISSUE THREAD

**Issue by rmoradc** [SE761Team4/jabref#25]
**User Story**

As a developer, I would like to have a functional prototype of the JabMap interface displayed so that I can work on more features for JabMap  
**Acceptance Criteria**

- Basic GUI based on high-level UI designs displayed
- Code is easy to alter and add new features to

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

**Describe the solution you'd like**

The screen should have the basic layout and look and feel of the UI diagram.

**Comment by koppor** [comment]
Additinal acceptance criteria: 

- Add [ADR](https://adr.github.io/madr/) on the chosen implementation. [Angular](https://angular.io/) vs. [Vue.js](https://vuejs.org/) vs. [React](https://reactjs.org/). - A basic reason can be: "More experiences in React than in Vue.js available in the implementation team".

**Comment by rmoradc** [comment]
React is better because more team experience.
