### ISSUE TITLE
[4pt] Make BibTeX to MindMap parser

### ISSUE THREAD

**Issue by rmoradc** [SE761Team4/jabref#38]
**User Story**

As a developer, I would like to map BibTex to JSON so that I can parse information to JabMap
**Acceptance Criteria**

- BibTeX data can be parsed via HTTP to JabMap

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

**Describe the solution you'd like**

**Comment by koppor** [comment]
Refs https://github.com/SE761Team4/jabref/issues/13.

Two aspects:

- BibTeX to JSON (MindMap) ("BibTeX2MindMap" --> internal JabRef Java MindMap model and Jackson JSON generation)
- JSON (MindMap) to BibTeX

Implementation details:

- Java data model for a MindMap -> https://github.com/SE761Team4/jabref/issues/41
- JSON-serialization of that data model (probably Jackson as library) -> produces the data format described at https://github.com/SE761Team4/jabref/issues/41
- JabMap reads JSON
- REST-API accepts JSON (facing JabMap) -> https://github.com/SE761Team4/jabref/issues/23
- REST-API produces JSON (facing JabMap) -> https://github.com/SE761Team4/jabref/issues/23
- REST-API uses BibTeX2MindMap conversion
- REST-API uses MindMap2BibTeX conversion

![grafik](https://user-images.githubusercontent.com/1366654/91399901-1a4c1980-e83f-11ea-8259-3a0a93250d2b.png)

**Comment by rmoradc** [comment]
Thanks for the extra detail and diagram.
