### ISSUE TITLE
[2pt] UI design conventions (look and feel)

### ISSUE THREAD

**Issue by isabellelucy** [SE761Team4/jabref#57]
As a user I would like a clean UI that matches Jabref's design conventions so that I am familiar with the JabMap interface

- UI design needs to be done so that it matches Jabref conventions and prototypes

**Comment by koppor** [comment]
Screenshot following the JabRef style: https://github.com/SE761Team4/jabref/wiki/High-Fidelity-Prototype

(Alternative to https://www.thebrain.com/)
