### ISSUE TITLE
[6pt] Edit mmp 

### ISSUE THREAD

**Issue by rmoradc** [SE761Team4/jabref#78]
**User Story**

As a developer, I would like the mmp library to be able to support having icons and bib entries on nodes and smaller edges. 
**Acceptance Criteria**

- Icons stored on mmp node model 
- BibEntries stored on mmp node model
- mmp edges look appropriate

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

**Describe the solution you'd like**

**Comment by koppor** [comment]
Architect-job: Add mmap library to the ADR created while working on https://github.com/SE761Team4/jabref/issues/37
